require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PreferredAddressesController do

  # This should return the minimal set of attributes required to create a valid
  # PreferredAddress. As you add validations to PreferredAddress, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PreferredAddressesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all preferred_addresses as @preferred_addresses" do
      preferred_address = PreferredAddress.create! valid_attributes
      get :index, {}, valid_session
      assigns(:preferred_addresses).should eq([preferred_address])
    end
  end

  describe "GET show" do
    it "assigns the requested preferred_address as @preferred_address" do
      preferred_address = PreferredAddress.create! valid_attributes
      get :show, {:id => preferred_address.to_param}, valid_session
      assigns(:preferred_address).should eq(preferred_address)
    end
  end

  describe "GET new" do
    it "assigns a new preferred_address as @preferred_address" do
      get :new, {}, valid_session
      assigns(:preferred_address).should be_a_new(PreferredAddress)
    end
  end

  describe "GET edit" do
    it "assigns the requested preferred_address as @preferred_address" do
      preferred_address = PreferredAddress.create! valid_attributes
      get :edit, {:id => preferred_address.to_param}, valid_session
      assigns(:preferred_address).should eq(preferred_address)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PreferredAddress" do
        expect {
          post :create, {:preferred_address => valid_attributes}, valid_session
        }.to change(PreferredAddress, :count).by(1)
      end

      it "assigns a newly created preferred_address as @preferred_address" do
        post :create, {:preferred_address => valid_attributes}, valid_session
        assigns(:preferred_address).should be_a(PreferredAddress)
        assigns(:preferred_address).should be_persisted
      end

      it "redirects to the created preferred_address" do
        post :create, {:preferred_address => valid_attributes}, valid_session
        response.should redirect_to(PreferredAddress.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved preferred_address as @preferred_address" do
        # Trigger the behavior that occurs when invalid params are submitted
        PreferredAddress.any_instance.stub(:save).and_return(false)
        post :create, {:preferred_address => {}}, valid_session
        assigns(:preferred_address).should be_a_new(PreferredAddress)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PreferredAddress.any_instance.stub(:save).and_return(false)
        post :create, {:preferred_address => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested preferred_address" do
        preferred_address = PreferredAddress.create! valid_attributes
        # Assuming there are no other preferred_addresses in the database, this
        # specifies that the PreferredAddress created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PreferredAddress.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => preferred_address.to_param, :preferred_address => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested preferred_address as @preferred_address" do
        preferred_address = PreferredAddress.create! valid_attributes
        put :update, {:id => preferred_address.to_param, :preferred_address => valid_attributes}, valid_session
        assigns(:preferred_address).should eq(preferred_address)
      end

      it "redirects to the preferred_address" do
        preferred_address = PreferredAddress.create! valid_attributes
        put :update, {:id => preferred_address.to_param, :preferred_address => valid_attributes}, valid_session
        response.should redirect_to(preferred_address)
      end
    end

    describe "with invalid params" do
      it "assigns the preferred_address as @preferred_address" do
        preferred_address = PreferredAddress.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PreferredAddress.any_instance.stub(:save).and_return(false)
        put :update, {:id => preferred_address.to_param, :preferred_address => {}}, valid_session
        assigns(:preferred_address).should eq(preferred_address)
      end

      it "re-renders the 'edit' template" do
        preferred_address = PreferredAddress.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PreferredAddress.any_instance.stub(:save).and_return(false)
        put :update, {:id => preferred_address.to_param, :preferred_address => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested preferred_address" do
      preferred_address = PreferredAddress.create! valid_attributes
      expect {
        delete :destroy, {:id => preferred_address.to_param}, valid_session
      }.to change(PreferredAddress, :count).by(-1)
    end

    it "redirects to the preferred_addresses list" do
      preferred_address = PreferredAddress.create! valid_attributes
      delete :destroy, {:id => preferred_address.to_param}, valid_session
      response.should redirect_to(preferred_addresses_url)
    end
  end

end
